# Generated by Django 5.0.1 on 2024-03-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passrecovery',
            name='email',
            field=models.EmailField(default='josecarlosv8474@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
