# Generated by Django 5.0.1 on 2024-01-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leite',
            name='data',
            field=models.DateField(unique=True),
        ),
    ]
