# Generated by Django 5.0.1 on 2024-01-19 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leite', '0002_alter_leite_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='soma',
            name='data_fim',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soma',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
