# Generated by Django 5.0.1 on 2024-01-19 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leite', '0003_soma_data_fim_soma_data_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leite',
            old_name='id_soma',
            new_name='soma',
        ),
    ]
