# Generated by Django 5.0.1 on 2024-01-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leite', '0005_leite_usuario_soma_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leite',
            name='data',
            field=models.DateField(),
        ),
    ]
